---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- include: pip.yml
- include: deploy.yml
- include: rabbitmq.yml
- include: var.yml
